import time
from utils import load_data, print_state
from bin_packing import BinPacking
from objective_function import calculate_objective, get_num_bins
from hill_climbing import (steepest_ascent_hill_climbing, stochastic_hill_climbing, sideways_move_hill_climbing, random_restart_hill_climbing)
from simulated_annealing import simulated_annealing
from genetic_algorithm import genetic_algorithm